function ASEN1022Feb21BrittleData = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ASEN1022FEB21BRITTLEDATA = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  ASEN1022FEB21BRITTLEDATA = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ASEN1022Feb21BrittleData = importfile("C:\Users\aelog\Documents\MATLAB\ASEN\Tensile Lab\ASEN1022_Feb21_Brittle_Data.csv", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Mar-2020 08:16:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Crosshead", "Load", "Time", "Extensometer"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ASEN1022Feb21BrittleData = readtable(filename, opts);

end